### ISSUE TITLE
GoBgp gRPC Java client is not working with Gradle protobuf plugin

### ISSUE THREAD

**Issue by Marty-Github** [ng-labo/gobgp-grpc-java#1]
Hello,

I'm trying to implement [gobgp grpc java client](https://github.com/Marty-Github/gobgp-grpc-java-client) by means of gradle build tool.
Projects [grpc-java](https://github.com/grpc/grpc-java) and [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin) are used as dependencies and plugin. It's building and running with error:

```
io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service apipb.GobgpApi
at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
at apipb.GobgpApiGrpc$GobgpApiBlockingStub.getBgp(GobgpApiGrpc.java:3033)
at grpc.Client.build_path(Client.java:80)
at grpc.Client.process(Client.java:123)
at grpc.Client.main(Client.java:136)
```

The **_*.proto_** files are taken from [gobgp/api](https://github.com/osrg/gobgp/tree/master/api) .

Your project uses Maven tool and I haven't succeeded to build it. I use java client's source code from your example in my project.

My environment:
OS: Windows 10 => WSL2 => Ubuntu 20.04
JDK: java-11-openjdk (linux)

```$>java -version```  
_openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)_

GoBgp service is installed under WSL2(Ubuntu 20.04) by command:  
```$>sudo apt-get -y install gobgpd```

GoBgp's version:  
```$>apt-cache policy gobgpd```  
_gobgpd:  
  Installed: 2.12.0-1  
  Candidate: 2.12.0-1  
  Version table:  
 *** 2.12.0-1 500  
    500 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages  100 /var/lib/dpkg/status_  

GoBgp service is runnig with configuration file taken from your [Getting Started](https://github.com/osrg/gobgp/blob/master/docs/sources/getting-started.md).  
GoBgp CLI is working well. All commands are executed.  

Could you please take a glance what's wrong with my project.
Is there any working gradle example of grpc java client for gobgp?

Thanks

**Comment by ng-labo** [comment]
Thanks for lighting my rudimentary coding.

I advice that you take *.proto of version 2.x in gobgp repogitory if my project will build.
It seems that package name that generated protobuf code by protoc is different between 2.x and latest. 

Now, after failed to build using *.proto from master version I succeessed it with others version *.proto.
`wget https://raw.githubusercontent.com/osrg/gobgp/v2.34.0/api/{attribute,gobgp,capability}.proto `

Even I do not know gradle usual because no chance to use,I guess it doesnt matter to build gobgp client project by any build tool supporting plugin for protoc.

**Comment by Marty-Github** [comment]
Thank you for response

Yes, these is no longer any error with *.proto of version 2.x .
But path isn't added/deleted again. I suspect gobgp server's binary release should be reinstalled to version 2.x as well.
I mean it's necessary to downgrade gobgp's linux package.
Unfortunately in our project we must use the latest v3.7 release.
So, I have to implement new grpc-java client for the latest version 3.7 .

Do you have any update of your client's example for version 3.7 ?  :)

**Comment by ng-labo** [comment]
It seems that api namespace has been changed from "gobgpapi" to "abipb", and some members name are updated in difference of gobgp.proto between 2.34 and 3.7.

How about such update?
```
nao@LAPTOP-X280:~/github.com/gobgp-grpc-java$ git diff src/main/java/gobgpapi/example/Client.java
diff --git a/src/main/java/gobgpapi/example/Client.java b/src/main/java/gobgpapi/example/Client.java
index 0fe8529..ee80ccf 100644
--- a/src/main/java/gobgpapi/example/Client.java
+++ b/src/main/java/gobgpapi/example/Client.java
@@ -4,11 +4,11 @@ import com.google.protobuf.Any;
 import io.grpc.Channel;
 import io.grpc.ManagedChannel;
 import io.grpc.ManagedChannelBuilder;
-import gobgpapi.GobgpApiGrpc;
+import apipb.GobgpApiGrpc;
 //import gobgpapi.GobgpApiGrpc.GobgpApiStub;
-import gobgpapi.GobgpApiGrpc.GobgpApiBlockingStub;
-import gobgpapi.Gobgp;
-import gobgpapi.Attribute;
+import apipb.GobgpApiGrpc.GobgpApiBlockingStub;
+import apipb.Gobgp;
+import apipb.Attribute;
 import java.util.List;

 public class Client {
@@ -75,7 +75,7 @@ public class Client {

         // retrive BgpResponse
         Gobgp.GetBgpResponse r = blockingStub.getBgp(Gobgp.GetBgpRequest.newBuilder().build());
-        int asn = r.getGlobal().getAs();
+        int asn = r.getGlobal().getAsn();

         // make nlri
         List<Any> rules = new java.util.ArrayList<Any>();
```

This works gobgpd-3.7 with just only global asn setting.

```
nao@LAPTOP-X280:~/gobgpd-3.7$ cat cfg
[global.config]
  as = 65001
  router-id = "0.0.0.0"
  local-address-list = ["0.0.0.0"]

nao@LAPTOP-X280:~/gobgpd-3.7$ ./gobgp global rib -a ipv4-flowspec
   Network                                                                              Next Hop             AS_PATH              Age        Attrs
*> [destination: 1.2.3.4/32][source: 5.6.7.8/32][protocol: ==udp][port: ==1900 ==11211] fictitious                                00:04:01   [{Extcomms: [discard]} {Origin: i}]
```

**Comment by Marty-Github** [comment]
I've tryed. It doesn't help.

It seems to me that version of default ubuntu's gobgp installation is incompatible. I mean it isn't 3.7 version.
And one more, as I know grpc server must be registered on server. Probably gobgp service doesn't register itself correctly.

I'll proceed with my attempts.
In any case thank you very much for your participation!

**Comment by ng-labo** [comment]
It was fun for me to check out the latest version of gobgp after long.
I hope your  project of BGP going well !
